/*
 * This source file was generated by the Gradle 'init' task
 */
package no.setup.bankers;

import no.setup.bankers.persistence.Db;


public class App {
    public static void main(String[] args) {
        // Initiliazes 
        Db.migrate();
    }
}
